import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeClient from "@/components/theme/client";
import { Toaster } from "@/components/ui/toaster";
import { Header } from "@/components/ui/header";
import ThemeToggle from "@/components/theme/theme-toggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FileForge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeClient>
          {children}
          <Toaster />
          <ThemeToggle />
        </ThemeClient>
      </body>
    </html>
  );
}
